### ISSUE TITLE
Development setup doesn't work on MacOS

### ISSUE THREAD

**Issue by Tethik** [klarna-incubator/gram#54]
Connectivity between postgres container and the Gram API seems to fail.

**Comment by Tethik** [comment]
This may already be fixed since we moved the default config to use `127.0.0.1` instead of `localhost` for the postgres host. Will leave this issue open for now and close it later if we don't hear anything new.

**Comment by Pulko** [comment]
I'll take care of it ☺️

**Comment by Pulko** [comment]
hey @Tethik  :) 

Sorry for a big delay. I finally managed to start it out.

I wonder what would be a point when we can decide if it works for macOS. I have successfully started it, logged in and had some debug logs identifying that postgres connection is working (I suppose).

```
[2024-03-12T17:54:41.130] [DEBUG] postgres -
    UPDATE notifications
    SET status = 'pending', updated_at = current_timestamp
    WHERE id in (
        SELECT id FROM notifications
        WHERE status = 'new'
        ORDER BY updated_at ASC
        LIMIT 25
    )
    RETURNING *
[2024-03-12T17:54:41.151] [DEBUG] NotificationSender - No new notifications to send
```

Could that be an evidence?

**Comment by Tethik** [comment]
@Pulko as long as you can start it, login via the webapp, I think that's fine and we can close this issue. What was missing here was someone with a Mac to test it. Thanks for taking the time :)
